version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command:
            - /var/www/html/docker/run.sh
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        networks:
            - teste-php-laravel
        depends_on:
            - postgres
    postgres:
        image: mdillon/postgis:11
        volumes:
            - .:/tmp
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: pg01
            POSTGRES_USER: postgres
        ports:
            - "5432:5432"
        networks:
            - teste-php-laravel
networks:
    teste-php-laravel:
        driver: bridge
